version: "3.3"

services:
  web:
    build: ./sainikBackend
    # command: gunicorn sainikBackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./sainikBackend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx_sites
    ports:
      - 80:80
    depends_on:
      - web
      - reactjs
    volumes:
      - ./sainikBackend/:/usr/src/app/
      - ./sainikFrontend/public/:/usr/src/app/static/

  reactjs:
    build: ./sainikFrontend
    ports:
      - 3000:3000
    stdin_open: true
    command: bash -c "npm install && npm start"
    volumes:
      - ./sainikFrontend/:/usr/app/
