# Generated by Django 3.0.6 on 2020-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthDetails',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('userType', models.CharField(choices=[('KSB', 'Kendriya Sainik Board'), ('RSB', 'Rajya Sainik Board'), ('ZSB', 'Zilla Sainik Board'), ('USR', 'User')], default='USR', max_length=10)),
                ('userCategory', models.CharField(choices=[('ESM', 'Ex Service men'), ('OFF', 'Officers'), ('MNS', 'Military Nursing Services'), ('APS', 'Army Postal Services'), ('WIDDOW', 'Widow'), ('BRD', 'Board')], default='ESM', max_length=10)),
                ('approvalStatus', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=10)),
                ('documents', models.FileField(upload_to='')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'UserAuthDetails',
            },
        ),
    ]
