# Generated by Django 3.0.6 on 2020-05-31 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('maritalStatus', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorcee')], default='M', max_length=10)),
                ('marriageDate', models.DateField()),
                ('spouseName', models.CharField(max_length=20)),
                ('spouseRelation', models.CharField(choices=[('W', 'Wife'), ('H', 'Husband')], default='W', max_length=8)),
                ('spouseDOB', models.DateField()),
                ('spouseID', models.CharField(max_length=20)),
                ('spouseQualification', models.CharField(max_length=25)),
                ('spouseEmpStatus', models.CharField(choices=[('E', 'Employed'), ('U', 'Un employed')], default='U', max_length=10)),
                ('spouseEmpProf', models.CharField(max_length=25)),
                ('spouseRetirementDate', models.DateField()),
                ('nextOfKin', models.CharField(max_length=25)),
                ('relationToESM', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FamilyDetails',
            },
        ),
        migrations.CreateModel(
            name='DependentDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfDependent', models.CharField(max_length=25)),
                ('dependentRelation', models.CharField(choices=[('S', 'Son'), ('D', 'Daughter'), ('F', 'Father'), ('M', 'Mother')], default='S', max_length=10)),
                ('DOB', models.DateField()),
                ('qualification', models.CharField(max_length=25)),
                ('academicYear', models.PositiveIntegerField()),
                ('empStatus', models.CharField(choices=[('E', 'Employed'), ('U', 'Un employed')], default='U', max_length=10)),
                ('maritalStatus', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorcee')], default='M', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DependentDetails',
            },
        ),
    ]
