# Generated by Django 3.0.6 on 2020-05-31 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('idMark', models.CharField(max_length=50)),
                ('aadharNum', models.PositiveIntegerField()),
                ('panNum', models.CharField(max_length=15)),
                ('echsCardNum', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('caste', models.CharField(blank=True, max_length=20, null=True)),
                ('birthPlace', models.CharField(max_length=30)),
                ('birthState', models.CharField(max_length=25)),
                ('birthCity', models.CharField(max_length=30)),
                ('eduQualInCivil', models.CharField(max_length=20)),
                ('eduQualInService', models.CharField(blank=True, max_length=20, null=True)),
                ('isCivilEmployed', models.BooleanField(default=False)),
                ('isCivilPensioner', models.BooleanField(default=False)),
                ('civilPensionAmount', models.PositiveIntegerField(default=0)),
                ('civilEmployer', models.CharField(blank=True, max_length=25, null=True)),
                ('monthlyIncome', models.PositiveIntegerField(default=0)),
                ('deptInCivil', models.CharField(blank=True, max_length=25, null=True)),
                ('civilDateRetirement', models.DateField(blank=True, null=True)),
                ('officialContactNum', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PersonalDetails',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('mobileNumber', models.PositiveIntegerField()),
                ('telephoneNumber', models.PositiveIntegerField()),
                ('emailAddress', models.EmailField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('streetAddress', models.CharField(max_length=45)),
                ('houseNumber', models.CharField(max_length=10)),
                ('policeStation', models.CharField(max_length=30)),
                ('tempOrPerm', models.CharField(blank=True, choices=[('T', 'Temporary'), ('P', 'Permanent')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContactDetails',
            },
        ),
    ]
